# Pandas

### Importing Pandas

In [1]:
import numpy as np
import pandas as pd

### Data Structures in Pandas

`Series`:  one-dimensional labeled array holding data of any type.

`DataFrame`: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

### Creating Objects
Creating a `Series` by passing a list of values, letting pandas create a default `RangeIndex`.

In [2]:
pd_series = pd.Series([1,3,5,7,np.nan,11,13])

In [3]:
pd_series

0     1.0
1     3.0
2     5.0
3     7.0
4     NaN
5    11.0
6    13.0
dtype: float64

Creating a `DataFrame` by passing a NumPy array with a datetime index using `date_range()` and labeled columns:

In [4]:
date_pd = pd.date_range('20160101', periods=10)

In [5]:
date_pd

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
               '2016-01-09', '2016-01-10'],
              dtype='datetime64[ns]', freq='D')

In [6]:
arr_df =  pd.DataFrame(np.random.randn(10, 4), index=date_pd, columns=list("ABCD"))

In [7]:
arr_df

                   A         B         C         D
2016-01-01 -0.764477 -1.301132 -0.712767  0.892384
2016-01-02 -0.473279 -0.514199 -0.820494 -1.502410
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962
2016-01-04  0.780049 -0.364146  0.281019 -0.450148
2016-01-05 -1.588715  0.036778  0.468016 -0.837232
2016-01-06 -1.436593  1.021036  1.245539  1.393994
2016-01-07 -0.260317  1.824841  0.437538 -0.244887
2016-01-08  0.541865 -0.662170  1.056104 -0.623393
2016-01-09  0.804712  0.241560  0.188212  1.058451
2016-01-10 -0.126392  0.387062  1.430067  0.598906

Creating a `DataFrame` from a dictionary where the keys are the column labels and the values are column values.

In [8]:
dict_df = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

In [9]:
dict_df

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [10]:
dict_df.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

### Viewing Data
`DataFrame.head()`, `DataFrame.tail()`

`DataFrame.head()`: is used to view the top rows of the frame

`DataFrame.tail()`: is used to view the bottom rows of the frame.

In [11]:
arr_df.head()

                   A         B         C         D
2016-01-01 -0.764477 -1.301132 -0.712767  0.892384
2016-01-02 -0.473279 -0.514199 -0.820494 -1.502410
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962
2016-01-04  0.780049 -0.364146  0.281019 -0.450148
2016-01-05 -1.588715  0.036778  0.468016 -0.837232

In [12]:
arr_df.tail()

                   A         B         C         D
2016-01-06 -1.436593  1.021036  1.245539  1.393994
2016-01-07 -0.260317  1.824841  0.437538 -0.244887
2016-01-08  0.541865 -0.662170  1.056104 -0.623393
2016-01-09  0.804712  0.241560  0.188212  1.058451
2016-01-10 -0.126392  0.387062  1.430067  0.598906

`DataFrame.index `: to show the indices of the DataFrame

`DataFrame.columns`: to display the columns of the DataFrame

In [13]:
arr_df.index

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
               '2016-01-09', '2016-01-10'],
              dtype='datetime64[ns]', freq='D')

In [14]:
arr_df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

`DataFrame.to_numpy()`: Used to return a Numpy represenation of the underlying data with or without index or column labels.

In [15]:
arr_df.to_numpy()

array([[-0.76447698, -1.30113167, -0.71276667,  0.89238439],
       [-0.47327882, -0.51419925, -0.82049351, -1.50240974],
       [-0.6893484 ,  1.03001435, -1.09839559, -0.29996211],
       [ 0.78004889, -0.36414598,  0.28101884, -0.45014768],
       [-1.5887152 ,  0.03677799,  0.46801593, -0.83723241],
       [-1.43659298,  1.02103628,  1.24553892,  1.39399437],
       [-0.26031664,  1.82484081,  0.43753847, -0.24488728],
       [ 0.54186462, -0.66216982,  1.05610387, -0.62339251],
       [ 0.80471224,  0.2415605 ,  0.1882118 ,  1.05845073],
       [-0.12639174,  0.3870616 ,  1.4300674 ,  0.59890551]])

_**Note**_

NumPy arrays have one `dtype` for the entire array while pandas `DataFrames` have one dtype per column. When you call `DataFrame.to_numpy()`, pandas will find the NumPy dtype that can hold all of the dtypes in the DataFrame. If the common data type is `object`, `DataFrame.to_numpy()` will require copying data.

In [16]:
arr_df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [17]:
arr_df.to_numpy()

array([[-0.76447698, -1.30113167, -0.71276667,  0.89238439],
       [-0.47327882, -0.51419925, -0.82049351, -1.50240974],
       [-0.6893484 ,  1.03001435, -1.09839559, -0.29996211],
       [ 0.78004889, -0.36414598,  0.28101884, -0.45014768],
       [-1.5887152 ,  0.03677799,  0.46801593, -0.83723241],
       [-1.43659298,  1.02103628,  1.24553892,  1.39399437],
       [-0.26031664,  1.82484081,  0.43753847, -0.24488728],
       [ 0.54186462, -0.66216982,  1.05610387, -0.62339251],
       [ 0.80471224,  0.2415605 ,  0.1882118 ,  1.05845073],
       [-0.12639174,  0.3870616 ,  1.4300674 ,  0.59890551]])

`describe`: Used to show a quick statistic summary of the data.

In [18]:
arr_df.describe()

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.321250   0.169964   0.247484  -0.001430
std     0.848058   0.935862   0.882668   0.937962
min    -1.588715  -1.301132  -1.098396  -1.502410
25%    -0.745695  -0.476686  -0.487522  -0.580081
50%    -0.366798   0.139169   0.359279  -0.272425
75%     0.374801   0.862543   0.909082   0.819015
max     0.804712   1.824841   1.430067   1.393994

In [19]:
# Transposing
arr_df.T

,2016-01-01,2016-01-02,2016-01-03,2016-01-04,2016-01-05,2016-01-06,2016-01-07,2016-01-08,2016-01-09,2016-01-10
A,-0.764477,-0.473279,-0.689348,0.780049,-1.588715,-1.436593,-0.260317,0.541865,0.804712,-0.126392
B,-1.301132,-0.514199,1.030014,-0.364146,0.036778,1.021036,1.824841,-0.662170,0.241560,0.387062
C,-0.712767,-0.820494,-1.098396,0.281019,0.468016,1.245539,0.437538,1.056104,0.188212,1.430067
D,0.892384,-1.502410,-0.299962,-0.450148,-0.837232,1.393994,-0.244887,-0.623393,1.058451,0.598906

`DataFrame.sort_index()`: Used for sorting by axis

In [20]:
arr_df.sort_index(axis=0,  ascending=False)

                   A         B         C         D
2016-01-10 -0.126392  0.387062  1.430067  0.598906
2016-01-09  0.804712  0.241560  0.188212  1.058451
2016-01-08  0.541865 -0.662170  1.056104 -0.623393
2016-01-07 -0.260317  1.824841  0.437538 -0.244887
2016-01-06 -1.436593  1.021036  1.245539  1.393994
2016-01-05 -1.588715  0.036778  0.468016 -0.837232
2016-01-04  0.780049 -0.364146  0.281019 -0.450148
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962
2016-01-02 -0.473279 -0.514199 -0.820494 -1.502410
2016-01-01 -0.764477 -1.301132 -0.712767  0.892384

`DataFrame.sort_values()`: Sorts by values

In [21]:
arr_df.sort_values(by='D')

                   A         B         C         D
2016-01-02 -0.473279 -0.514199 -0.820494 -1.502410
2016-01-05 -1.588715  0.036778  0.468016 -0.837232
2016-01-08  0.541865 -0.662170  1.056104 -0.623393
2016-01-04  0.780049 -0.364146  0.281019 -0.450148
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962
2016-01-07 -0.260317  1.824841  0.437538 -0.244887
2016-01-10 -0.126392  0.387062  1.430067  0.598906
2016-01-01 -0.764477 -1.301132 -0.712767  0.892384
2016-01-09  0.804712  0.241560  0.188212  1.058451
2016-01-06 -1.436593  1.021036  1.245539  1.393994

In [22]:
arr_df.loc()

In [23]:
arr_df.iloc()

### Getitem([])

In [24]:
arr_df['A']

2016-01-01   -0.764477
2016-01-02   -0.473279
2016-01-03   -0.689348
2016-01-04    0.780049
2016-01-05   -1.588715
2016-01-06   -1.436593
2016-01-07   -0.260317
2016-01-08    0.541865
2016-01-09    0.804712
2016-01-10   -0.126392
Freq: D, Name: A, dtype: float64

In [25]:
# If the label only contains letters, numbers, and underscores,
# you can alternatively use the column name attribute
arr_df.A

2016-01-01   -0.764477
2016-01-02   -0.473279
2016-01-03   -0.689348
2016-01-04    0.780049
2016-01-05   -1.588715
2016-01-06   -1.436593
2016-01-07   -0.260317
2016-01-08    0.541865
2016-01-09    0.804712
2016-01-10   -0.126392
Freq: D, Name: A, dtype: float64

In [26]:
# Passing a list of column labels selects multiple columns,
# which can be useful for getting a subset/rearranging

arr_df[['C', 'B']]

                   C         B
2016-01-01 -0.712767 -1.301132
2016-01-02 -0.820494 -0.514199
2016-01-03 -1.098396  1.030014
2016-01-04  0.281019 -0.364146
2016-01-05  0.468016  0.036778
2016-01-06  1.245539  1.021036
2016-01-07  0.437538  1.824841
2016-01-08  1.056104 -0.662170
2016-01-09  0.188212  0.241560
2016-01-10  1.430067  0.387062

In [27]:
# For a DataFrame, passing a slice : selects matching rows

arr_df[0:3]

                   A         B         C         D
2016-01-01 -0.764477 -1.301132 -0.712767  0.892384
2016-01-02 -0.473279 -0.514199 -0.820494 -1.502410
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962

In [28]:
arr_df['20160103':'20160106']

                   A         B         C         D
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962
2016-01-04  0.780049 -0.364146  0.281019 -0.450148
2016-01-05 -1.588715  0.036778  0.468016 -0.837232
2016-01-06 -1.436593  1.021036  1.245539  1.393994

##### Selection by Label
Selecting a row matching a label

In [29]:
arr_df.loc[date_pd[0]]

A   -0.764477
B   -1.301132
C   -0.712767
D    0.892384
Name: 2016-01-01 00:00:00, dtype: float64

Selecting all rows (:) with a select column labels:

In [30]:
arr_df.loc[:, ['A', 'B']]

                   A         B
2016-01-01 -0.764477 -1.301132
2016-01-02 -0.473279 -0.514199
2016-01-03 -0.689348  1.030014
2016-01-04  0.780049 -0.364146
2016-01-05 -1.588715  0.036778
2016-01-06 -1.436593  1.021036
2016-01-07 -0.260317  1.824841
2016-01-08  0.541865 -0.662170
2016-01-09  0.804712  0.241560
2016-01-10 -0.126392  0.387062

For label slicing, both endpoints are included

In [31]:
arr_df.loc['20160102':'20160107', ['A', 'C']]

                   A         C
2016-01-02 -0.473279 -0.820494
2016-01-03 -0.689348 -1.098396
2016-01-04  0.780049  0.281019
2016-01-05 -1.588715  0.468016
2016-01-06 -1.436593  1.245539
2016-01-07 -0.260317  0.437538

Selecting a single row and column label returns a scalar

In [32]:
arr_df.loc[date_pd[0], 'C']

np.float64(-0.7127666727443404)

In [33]:
# For getting fast access to a scalar (equivalent to the prior method)
arr_df.at[date_pd[0], 'C']

np.float64(-0.7127666727443404)

### Selection by Position
`.iloc()` and `.iat()`

The two methods helps us select the passed integers.

In [37]:
arr_df

                   A         B         C         D
2016-01-01 -0.764477 -1.301132 -0.712767  0.892384
2016-01-02 -0.473279 -0.514199 -0.820494 -1.502410
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962
2016-01-04  0.780049 -0.364146  0.281019 -0.450148
2016-01-05 -1.588715  0.036778  0.468016 -0.837232
2016-01-06 -1.436593  1.021036  1.245539  1.393994
2016-01-07 -0.260317  1.824841  0.437538 -0.244887
2016-01-08  0.541865 -0.662170  1.056104 -0.623393
2016-01-09  0.804712  0.241560  0.188212  1.058451
2016-01-10 -0.126392  0.387062  1.430067  0.598906

In [36]:
# Example iloc
arr_df.iloc[2]

A   -0.689348
B    1.030014
C   -1.098396
D   -0.299962
Name: 2016-01-03 00:00:00, dtype: float64

In [42]:
# Integer slices work similar to Numpy/Python slices
arr_df.iloc[3:6, 0:2]

                   A         B
2016-01-04  0.780049 -0.364146
2016-01-05 -1.588715  0.036778
2016-01-06 -1.436593  1.021036

In [50]:
# List of integer positions
arr_df.iloc[[1,2,8], [0,3]]

                   A         D
2016-01-02 -0.473279 -1.502410
2016-01-03 -0.689348 -0.299962
2016-01-09  0.804712  1.058451

In [52]:
# Slicing rows explicitly
arr_df.iloc[1:3, :]

                   A         B         C         D
2016-01-02 -0.473279 -0.514199 -0.820494 -1.502410
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962

In [53]:
# Slicing columns explicitly
arr_df.iloc[:, 0:2]

                   A         B
2016-01-01 -0.764477 -1.301132
2016-01-02 -0.473279 -0.514199
2016-01-03 -0.689348  1.030014
2016-01-04  0.780049 -0.364146
2016-01-05 -1.588715  0.036778
2016-01-06 -1.436593  1.021036
2016-01-07 -0.260317  1.824841
2016-01-08  0.541865 -0.662170
2016-01-09  0.804712  0.241560
2016-01-10 -0.126392  0.387062

In [56]:
# Getting a value explicitly
arr_df.iloc[2,3]

np.float64(-0.2999621129866171)

In [59]:
# For getting quickly a scalar equivalent prior method
arr_df.iat[2,3]

np.float64(-0.2999621129866171)

### Boolean Indexing

In [64]:
# Select a rows where df['B'] > 0

arr_df[arr_df['B'] > 0]

                   A         B         C         D
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962
2016-01-05 -1.588715  0.036778  0.468016 -0.837232
2016-01-06 -1.436593  1.021036  1.245539  1.393994
2016-01-07 -0.260317  1.824841  0.437538 -0.244887
2016-01-09  0.804712  0.241560  0.188212  1.058451
2016-01-10 -0.126392  0.387062  1.430067  0.598906

In [65]:
# Selecting values from a DataFrame where a condition is met

arr_df[arr_df > 0.5]

                   A         B         C         D
2016-01-01       NaN       NaN       NaN  0.892384
2016-01-02       NaN       NaN       NaN       NaN
2016-01-03       NaN  1.030014       NaN       NaN
2016-01-04  0.780049       NaN       NaN       NaN
2016-01-05       NaN       NaN       NaN       NaN
2016-01-06       NaN  1.021036  1.245539  1.393994
2016-01-07       NaN  1.824841       NaN       NaN
2016-01-08  0.541865       NaN  1.056104       NaN
2016-01-09  0.804712       NaN       NaN  1.058451
2016-01-10       NaN       NaN  1.430067  0.598906

Using the `.isin()` method.

In [72]:
arr_df_cp = arr_df.copy

In [73]:
arr_df_cp["E"] = ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten']

TypeError: 'method' object does not support item assignment

### Setting

Setting a new column automatically aligns the data by the indexes:

In [85]:
ser = pd.Series([1,2,3,4,5,6,7,8,9,10],
              pd.date_range("20160102", periods=10))

In [86]:
ser

2016-01-02     1
2016-01-03     2
2016-01-04     3
2016-01-05     4
2016-01-06     5
2016-01-07     6
2016-01-08     7
2016-01-09     8
2016-01-10     9
2016-01-11    10
Freq: D, dtype: int64

In [87]:
arr_df_cp1 = arr_df.copy()

In [88]:
arr_df_cp1["E"] = ser

In [89]:
arr_df_cp1

                   A         B         C         D    E
2016-01-01 -0.764477 -1.301132 -0.712767  0.892384  NaN
2016-01-02 -0.473279 -0.514199 -0.820494 -1.502410  1.0
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962  2.0
2016-01-04  0.780049 -0.364146  0.281019 -0.450148  3.0
2016-01-05 -1.588715  0.036778  0.468016 -0.837232  4.0
2016-01-06 -1.436593  1.021036  1.245539  1.393994  5.0
2016-01-07 -0.260317  1.824841  0.437538 -0.244887  6.0
2016-01-08  0.541865 -0.662170  1.056104 -0.623393  7.0
2016-01-09  0.804712  0.241560  0.188212  1.058451  8.0
2016-01-10 -0.126392  0.387062  1.430067  0.598906  9.0

In [92]:
# Setting values by label
arr_df_cp1.at[date_pd[1], "A"]  = 0

In [95]:
# Setting values by position
arr_df_cp1.iat[1,0] = 0

In [96]:
arr_df_cp1

                   A         B         C         D    E  (1, 0)
2016-01-01 -0.764477 -1.301132 -0.712767  0.892384  NaN       0
2016-01-02  0.000000 -0.514199 -0.820494 -1.502410  1.0       0
2016-01-03 -0.689348  1.030014 -1.098396 -0.299962  2.0       0
2016-01-04  0.780049 -0.364146  0.281019 -0.450148  3.0       0
2016-01-05 -1.588715  0.036778  0.468016 -0.837232  4.0       0
2016-01-06 -1.436593  1.021036  1.245539  1.393994  5.0       0
2016-01-07 -0.260317  1.824841  0.437538 -0.244887  6.0       0
2016-01-08  0.541865 -0.662170  1.056104 -0.623393  7.0       0
2016-01-09  0.804712  0.241560  0.188212  1.058451  8.0       0
2016-01-10 -0.126392  0.387062  1.430067  0.598906  9.0       0

In [98]:
# Setting by assigning with a NumPy array
arr_df_cp1.loc[:, "D"] = np.array([5] * len(arr_df_cp1))

In [99]:
arr_df_cp1

                   A         B         C    D    E  (1, 0)
2016-01-01 -0.764477 -1.301132 -0.712767  5.0  NaN       0
2016-01-02  0.000000 -0.514199 -0.820494  5.0  1.0       0
2016-01-03 -0.689348  1.030014 -1.098396  5.0  2.0       0
2016-01-04  0.780049 -0.364146  0.281019  5.0  3.0       0
2016-01-05 -1.588715  0.036778  0.468016  5.0  4.0       0
2016-01-06 -1.436593  1.021036  1.245539  5.0  5.0       0
2016-01-07 -0.260317  1.824841  0.437538  5.0  6.0       0
2016-01-08  0.541865 -0.662170  1.056104  5.0  7.0       0
2016-01-09  0.804712  0.241560  0.188212  5.0  8.0       0
2016-01-10 -0.126392  0.387062  1.430067  5.0  9.0       0

In [103]:
# A where operation with setting
arr_df_cp2 = arr_df.copy()

arr_df_cp2[arr_df_cp2 > 0] = -arr_df_cp2

arr_df_cp2

                   A         B         C         D    E
2016-01-01 -0.764477 -1.301132 -0.712767 -0.892384  NaN
2016-01-02 -0.473279 -0.514199 -0.820494 -1.502410 -1.0
2016-01-03 -0.689348 -1.030014 -1.098396 -0.299962 -2.0
2016-01-04 -0.780049 -0.364146 -0.281019 -0.450148 -3.0
2016-01-05 -1.588715 -0.036778 -0.468016 -0.837232 -4.0
2016-01-06 -1.436593 -1.021036 -1.245539 -1.393994 -5.0
2016-01-07 -0.260317 -1.824841 -0.437538 -0.244887 -6.0
2016-01-08 -0.541865 -0.662170 -1.056104 -0.623393 -7.0
2016-01-09 -0.804712 -0.241560 -0.188212 -1.058451 -8.0
2016-01-10 -0.126392 -0.387062 -1.430067 -0.598906 -9.0