# Pandas

### Importing Pandas

In [3]:
import numpy as np
import pandas as pd

### Data Structures in Pandas

`Series`:  one-dimensional labeled array holding data of any type.

`DataFrame`: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

### Creating Objects
Creating a `Series` by passing a list of values, letting pandas create a default `RangeIndex`.

In [4]:
pd_series = pd.Series([1,3,5,7,np.nan,11,13])

In [5]:
pd_series

0     1.0
1     3.0
2     5.0
3     7.0
4     NaN
5    11.0
6    13.0
dtype: float64

Creating a `DataFrame` by passing a NumPy array with a datetime index using `date_range()` and labeled columns:

In [6]:
date_pd = pd.date_range('20160101', periods=10)

In [7]:
date_pd

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
               '2016-01-09', '2016-01-10'],
              dtype='datetime64[ns]', freq='D')

In [8]:
arr_df =  pd.DataFrame(np.random.randn(10, 4), index=date_pd, columns=list("ABCD"))

In [9]:
arr_df

                   A         B         C         D
2016-01-01  1.326065 -0.988299 -0.695310 -1.582914
2016-01-02 -0.014446 -0.462387 -2.296426 -0.442625
2016-01-03 -0.571307  1.538250  0.299486  0.470941
2016-01-04 -0.309569 -0.691254  0.324153  0.904384
2016-01-05 -0.733819 -0.795605  0.378692  0.228240
2016-01-06 -1.531871 -0.238504 -0.708591  0.613365
2016-01-07  0.384514  1.926560 -0.002834  0.168278
2016-01-08  1.063724 -0.294760  1.217275 -0.217472
2016-01-09 -0.226979 -0.209225  0.454567 -0.758768
2016-01-10  0.508505  1.393794 -0.410377 -0.194962

Creating a `DataFrame` from a dictionary where the keys are the column labels and the values are column values.

In [10]:
dict_df = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

In [11]:
dict_df

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [12]:
dict_df.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

### Viewing Data
`DataFrame.head()`, `DataFrame.tail()`

`DataFrame.head()`: is used to view the top rows of the frame

`DataFrame.tail()`: is used to view the bottom rows of the frame.

In [13]:
arr_df.head()

                   A         B         C         D
2016-01-01  1.326065 -0.988299 -0.695310 -1.582914
2016-01-02 -0.014446 -0.462387 -2.296426 -0.442625
2016-01-03 -0.571307  1.538250  0.299486  0.470941
2016-01-04 -0.309569 -0.691254  0.324153  0.904384
2016-01-05 -0.733819 -0.795605  0.378692  0.228240

In [14]:
arr_df.tail()

                   A         B         C         D
2016-01-06 -1.531871 -0.238504 -0.708591  0.613365
2016-01-07  0.384514  1.926560 -0.002834  0.168278
2016-01-08  1.063724 -0.294760  1.217275 -0.217472
2016-01-09 -0.226979 -0.209225  0.454567 -0.758768
2016-01-10  0.508505  1.393794 -0.410377 -0.194962

`DataFrame.index `: to show the indices of the DataFrame

`DataFrame.columns`: to display the columns of the DataFrame

In [15]:
arr_df.index

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
               '2016-01-09', '2016-01-10'],
              dtype='datetime64[ns]', freq='D')

In [16]:
arr_df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

`DataFrame.to_numpy()`: Used to return a Numpy represenation of the underlying data with or without index or column labels.

In [17]:
arr_df.to_numpy()

array([[ 1.32606504, -0.98829861, -0.69530985, -1.58291368],
       [-0.01444575, -0.46238679, -2.29642642, -0.44262523],
       [-0.57130733,  1.53825039,  0.29948646,  0.4709415 ],
       [-0.30956855, -0.69125437,  0.32415335,  0.90438385],
       [-0.73381875, -0.79560467,  0.37869211,  0.22823956],
       [-1.53187061, -0.23850376, -0.70859107,  0.61336476],
       [ 0.38451446,  1.92656049, -0.00283434,  0.16827764],
       [ 1.06372393, -0.29476005,  1.21727503, -0.21747241],
       [-0.22697879, -0.20922454,  0.45456667, -0.75876819],
       [ 0.50850458,  1.39379417, -0.4103773 , -0.19496216]])

_**Note**_

NumPy arrays have one `dtype` for the entire array while pandas `DataFrames` have one dtype per column. When you call `DataFrame.to_numpy()`, pandas will find the NumPy dtype that can hold all of the dtypes in the DataFrame. If the common data type is `object`, `DataFrame.to_numpy()` will require copying data.

In [18]:
arr_df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [19]:
arr_df.to_numpy()

array([[ 1.32606504, -0.98829861, -0.69530985, -1.58291368],
       [-0.01444575, -0.46238679, -2.29642642, -0.44262523],
       [-0.57130733,  1.53825039,  0.29948646,  0.4709415 ],
       [-0.30956855, -0.69125437,  0.32415335,  0.90438385],
       [-0.73381875, -0.79560467,  0.37869211,  0.22823956],
       [-1.53187061, -0.23850376, -0.70859107,  0.61336476],
       [ 0.38451446,  1.92656049, -0.00283434,  0.16827764],
       [ 1.06372393, -0.29476005,  1.21727503, -0.21747241],
       [-0.22697879, -0.20922454,  0.45456667, -0.75876819],
       [ 0.50850458,  1.39379417, -0.4103773 , -0.19496216]])

`describe`: Used to show a quick statistic summary of the data.

In [20]:
arr_df.describe()

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.010518   0.117857  -0.143937  -0.081153
std     0.859868   1.073442   0.957249   0.729766
min    -1.531871  -0.988299  -2.296426  -1.582914
25%    -0.505873  -0.634037  -0.624077  -0.386337
50%    -0.120712  -0.266632   0.148326  -0.013342
75%     0.477507   0.993039   0.365057   0.410266
max     1.326065   1.926560   1.217275   0.904384

In [21]:
# Transposing
arr_df.T

,2016-01-01,2016-01-02,2016-01-03,2016-01-04,2016-01-05,2016-01-06,2016-01-07,2016-01-08,2016-01-09,2016-01-10
A,1.326065,-0.014446,-0.571307,-0.309569,-0.733819,-1.531871,0.384514,1.063724,-0.226979,0.508505
B,-0.988299,-0.462387,1.538250,-0.691254,-0.795605,-0.238504,1.926560,-0.294760,-0.209225,1.393794
C,-0.695310,-2.296426,0.299486,0.324153,0.378692,-0.708591,-0.002834,1.217275,0.454567,-0.410377
D,-1.582914,-0.442625,0.470941,0.904384,0.228240,0.613365,0.168278,-0.217472,-0.758768,-0.194962

`DataFrame.sort_index()`: Used for sorting by axis

In [22]:
arr_df.sort_index(axis=0,  ascending=False)

                   A         B         C         D
2016-01-10  0.508505  1.393794 -0.410377 -0.194962
2016-01-09 -0.226979 -0.209225  0.454567 -0.758768
2016-01-08  1.063724 -0.294760  1.217275 -0.217472
2016-01-07  0.384514  1.926560 -0.002834  0.168278
2016-01-06 -1.531871 -0.238504 -0.708591  0.613365
2016-01-05 -0.733819 -0.795605  0.378692  0.228240
2016-01-04 -0.309569 -0.691254  0.324153  0.904384
2016-01-03 -0.571307  1.538250  0.299486  0.470941
2016-01-02 -0.014446 -0.462387 -2.296426 -0.442625
2016-01-01  1.326065 -0.988299 -0.695310 -1.582914

`DataFrame.sort_values()`: Sorts by values

In [23]:
arr_df.sort_values(by='D')

                   A         B         C         D
2016-01-01  1.326065 -0.988299 -0.695310 -1.582914
2016-01-09 -0.226979 -0.209225  0.454567 -0.758768
2016-01-02 -0.014446 -0.462387 -2.296426 -0.442625
2016-01-08  1.063724 -0.294760  1.217275 -0.217472
2016-01-10  0.508505  1.393794 -0.410377 -0.194962
2016-01-07  0.384514  1.926560 -0.002834  0.168278
2016-01-05 -0.733819 -0.795605  0.378692  0.228240
2016-01-03 -0.571307  1.538250  0.299486  0.470941
2016-01-06 -1.531871 -0.238504 -0.708591  0.613365
2016-01-04 -0.309569 -0.691254  0.324153  0.904384

In [26]:
arr_df.loc()

In [27]:
arr_df.iloc()

### Getitem([])

In [29]:
arr_df['A']

2016-01-01    1.326065
2016-01-02   -0.014446
2016-01-03   -0.571307
2016-01-04   -0.309569
2016-01-05   -0.733819
2016-01-06   -1.531871
2016-01-07    0.384514
2016-01-08    1.063724
2016-01-09   -0.226979
2016-01-10    0.508505
Freq: D, Name: A, dtype: float64

In [32]:
# If the label only contains letters, numbers, and underscores,
# you can alternatively use the column name attribute
arr_df.A

2016-01-01    1.326065
2016-01-02   -0.014446
2016-01-03   -0.571307
2016-01-04   -0.309569
2016-01-05   -0.733819
2016-01-06   -1.531871
2016-01-07    0.384514
2016-01-08    1.063724
2016-01-09   -0.226979
2016-01-10    0.508505
Freq: D, Name: A, dtype: float64

In [34]:
# Passing a list of column labels selects multiple columns,
# which can be useful for getting a subset/rearranging

arr_df[['C', 'B']]

                   C         B
2016-01-01 -0.695310 -0.988299
2016-01-02 -2.296426 -0.462387
2016-01-03  0.299486  1.538250
2016-01-04  0.324153 -0.691254
2016-01-05  0.378692 -0.795605
2016-01-06 -0.708591 -0.238504
2016-01-07 -0.002834  1.926560
2016-01-08  1.217275 -0.294760
2016-01-09  0.454567 -0.209225
2016-01-10 -0.410377  1.393794

In [37]:
# For a DataFrame, passing a slice : selects matching rows

arr_df[0:3]

                   A         B         C         D
2016-01-01  1.326065 -0.988299 -0.695310 -1.582914
2016-01-02 -0.014446 -0.462387 -2.296426 -0.442625
2016-01-03 -0.571307  1.538250  0.299486  0.470941

In [38]:
arr_df['20160103':'20160106']

                   A         B         C         D
2016-01-03 -0.571307  1.538250  0.299486  0.470941
2016-01-04 -0.309569 -0.691254  0.324153  0.904384
2016-01-05 -0.733819 -0.795605  0.378692  0.228240
2016-01-06 -1.531871 -0.238504 -0.708591  0.613365

##### Selection by Label
Selecting a row matching a label

In [40]:
arr_df.loc[date_pd[0]]

A    1.326065
B   -0.988299
C   -0.695310
D   -1.582914
Name: 2016-01-01 00:00:00, dtype: float64

Selecting all rows (:) with a select column labels:

In [41]:
arr_df.loc[:, ['A', 'B']]

                   A         B
2016-01-01  1.326065 -0.988299
2016-01-02 -0.014446 -0.462387
2016-01-03 -0.571307  1.538250
2016-01-04 -0.309569 -0.691254
2016-01-05 -0.733819 -0.795605
2016-01-06 -1.531871 -0.238504
2016-01-07  0.384514  1.926560
2016-01-08  1.063724 -0.294760
2016-01-09 -0.226979 -0.209225
2016-01-10  0.508505  1.393794

For label slicing, both endpoints are included

In [42]:
arr_df.loc['20160102':'20160107', ['A', 'C']]

                   A         C
2016-01-02 -0.014446 -2.296426
2016-01-03 -0.571307  0.299486
2016-01-04 -0.309569  0.324153
2016-01-05 -0.733819  0.378692
2016-01-06 -1.531871 -0.708591
2016-01-07  0.384514 -0.002834

Selecting a single row and column label returns a scalar

In [45]:
arr_df.loc[date_pd[0], 'C']

np.float64(-0.6953098518764183)

In [47]:
# For getting fast access to a scalar (equivalent to the prior method)
arr_df.at[date_pd[0], 'C']

np.float64(-0.6953098518764183)