# Missing Data

`np.nan` in Numpy represents missing data. By default it is not included in computations.

Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data:

In [1]:
import numpy as np
import pandas as pd

In [2]:
date_pd = pd.date_range('20160101', periods=10)

In [3]:
arr_df =  pd.DataFrame(np.random.randn(10, 4), index=date_pd, columns=list("ABCD"))

In [4]:
ser = pd.Series([1,2,3,4,5,6,7,8,9,10],
              pd.date_range("20160102", periods=10))

In [5]:
arr_df["E"] = ser

In [6]:
arr_df.loc[:, "D"] = np.array([5] * len(arr_df))

In [7]:
arr_df

                   A         B         C    D    E
2016-01-01 -2.914352 -0.879452 -0.785130  5.0  NaN
2016-01-02  0.246162  0.262707 -0.746936  5.0  1.0
2016-01-03  1.105864 -0.899932 -0.153720  5.0  2.0
2016-01-04 -0.805555  0.133324 -0.243520  5.0  3.0
2016-01-05  0.653367  0.961763 -0.595552  5.0  4.0
2016-01-06 -0.166261 -0.201536  1.762890  5.0  5.0
2016-01-07 -0.433197  0.182401 -1.291754  5.0  6.0
2016-01-08 -0.449143  0.912506 -0.844436  5.0  7.0
2016-01-09  1.242747 -2.079887 -0.267063  5.0  8.0
2016-01-10 -0.034640 -0.598898 -0.464544  5.0  9.0

In [8]:
arr_df_reidx = arr_df.reindex(index=date_pd[0:9], columns=list(arr_df.columns) + ["E"])

In [9]:
arr_df_reidx.loc[date_pd[0]:date_pd[1], "E"] = 1

In [10]:
arr_df_reidx

                   A         B         C    D    E    E
2016-01-01 -2.914352 -0.879452 -0.785130  5.0  1.0  1.0
2016-01-02  0.246162  0.262707 -0.746936  5.0  1.0  1.0
2016-01-03  1.105864 -0.899932 -0.153720  5.0  2.0  2.0
2016-01-04 -0.805555  0.133324 -0.243520  5.0  3.0  3.0
2016-01-05  0.653367  0.961763 -0.595552  5.0  4.0  4.0
2016-01-06 -0.166261 -0.201536  1.762890  5.0  5.0  5.0
2016-01-07 -0.433197  0.182401 -1.291754  5.0  6.0  6.0
2016-01-08 -0.449143  0.912506 -0.844436  5.0  7.0  7.0
2016-01-09  1.242747 -2.079887 -0.267063  5.0  8.0  8.0

We use `DataFrame.dropna()` to drop any row with missing data.

In [11]:
arr_df_reidx.dropna(how="any")

                   A         B         C    D    E    E
2016-01-01 -2.914352 -0.879452 -0.785130  5.0  1.0  1.0
2016-01-02  0.246162  0.262707 -0.746936  5.0  1.0  1.0
2016-01-03  1.105864 -0.899932 -0.153720  5.0  2.0  2.0
2016-01-04 -0.805555  0.133324 -0.243520  5.0  3.0  3.0
2016-01-05  0.653367  0.961763 -0.595552  5.0  4.0  4.0
2016-01-06 -0.166261 -0.201536  1.762890  5.0  5.0  5.0
2016-01-07 -0.433197  0.182401 -1.291754  5.0  6.0  6.0
2016-01-08 -0.449143  0.912506 -0.844436  5.0  7.0  7.0
2016-01-09  1.242747 -2.079887 -0.267063  5.0  8.0  8.0

We use `DataFrame.fillna()` to fill any missing data.

In [12]:
arr_df_reidx.fillna(value=2)

                   A         B         C    D    E    E
2016-01-01 -2.914352 -0.879452 -0.785130  5.0  1.0  1.0
2016-01-02  0.246162  0.262707 -0.746936  5.0  1.0  1.0
2016-01-03  1.105864 -0.899932 -0.153720  5.0  2.0  2.0
2016-01-04 -0.805555  0.133324 -0.243520  5.0  3.0  3.0
2016-01-05  0.653367  0.961763 -0.595552  5.0  4.0  4.0
2016-01-06 -0.166261 -0.201536  1.762890  5.0  5.0  5.0
2016-01-07 -0.433197  0.182401 -1.291754  5.0  6.0  6.0
2016-01-08 -0.449143  0.912506 -0.844436  5.0  7.0  7.0
2016-01-09  1.242747 -2.079887 -0.267063  5.0  8.0  8.0

`isna()` gets the boolean mask where the value is `Nan`.

In [13]:
pd.isna(arr_df_reidx)

                A      B      C      D      E      E
2016-01-01  False  False  False  False  False  False
2016-01-02  False  False  False  False  False  False
2016-01-03  False  False  False  False  False  False
2016-01-04  False  False  False  False  False  False
2016-01-05  False  False  False  False  False  False
2016-01-06  False  False  False  False  False  False
2016-01-07  False  False  False  False  False  False
2016-01-08  False  False  False  False  False  False
2016-01-09  False  False  False  False  False  False

# Operations

### Stat
Operations generally exclude missing data. Example calculating the mean value for each column

In [14]:
arr_df_reidx.mean()

A   -0.168930
B   -0.178678
C   -0.351691
D    5.000000
E    4.111111
E    4.111111
dtype: float64

In [15]:
# Calculating the mean value for each row
arr_df_reidx.mean(axis=1)

2016-01-01    0.403511
2016-01-02    1.126989
2016-01-03    1.508702
2016-01-04    1.680708
2016-01-05    2.336596
2016-01-06    2.732515
2016-01-07    2.576242
2016-01-08    3.103155
2016-01-09    3.315966
Freq: D, dtype: float64

In [16]:
s = pd.Series([1, 3, 5, np.nan, 6, 8, np.nan,7,9,10], index=date_pd).shift(2)

In [17]:
arr_df_reidx.sub(s, axis="index")

                   A         B         C    D    E    E
2016-01-01       NaN       NaN       NaN  NaN  NaN  NaN
2016-01-02       NaN       NaN       NaN  NaN  NaN  NaN
2016-01-03  0.105864 -1.899932 -1.153720  4.0  1.0  1.0
2016-01-04 -3.805555 -2.866676 -3.243520  2.0  0.0  0.0
2016-01-05 -4.346633 -4.038237 -5.595552  0.0 -1.0 -1.0
2016-01-06       NaN       NaN       NaN  NaN  NaN  NaN
2016-01-07 -6.433197 -5.817599 -7.291754 -1.0  0.0  0.0
2016-01-08 -8.449143 -7.087494 -8.844436 -3.0 -1.0 -1.0
2016-01-09       NaN       NaN       NaN  NaN  NaN  NaN
2016-01-10       NaN       NaN       NaN  NaN  NaN  NaN

### User Defined Functions

`DataFrame.agg()` and `DataFrame.transform()` applies a user defined function that reduces or broadcasts its result respectively.

In [18]:
arr_df_reidx.agg(lambda x: np.mean(x) * 5.6)

A    -0.946006
B    -1.000599
C    -1.969471
D    28.000000
E    23.022222
E    23.022222
dtype: float64

In [19]:
arr_df_reidx.transform(lambda x: x * 101.2)

                     A           B           C      D      E      E
2016-01-01 -294.932401  -89.000512  -79.455145  506.0  101.2  101.2
2016-01-02   24.911601   26.585910  -75.589965  506.0  101.2  101.2
2016-01-03  111.913469  -91.073092  -15.556451  506.0  202.4  202.4
2016-01-04  -81.522155   13.492411  -24.644184  506.0  303.6  303.6
2016-01-05   66.120769   97.330446  -60.269905  506.0  404.8  404.8
2016-01-06  -16.825642  -20.395454  178.404500  506.0  506.0  506.0
2016-01-07  -43.839505   18.458933 -130.725528  506.0  607.2  607.2
2016-01-08  -45.453302   92.345646  -85.456924  506.0  708.4  708.4
2016-01-09  125.765977 -210.484594  -27.026809  506.0  809.6  809.6

### Value Counts

In [20]:
counts = pd.Series(np.random.randint(0, 7, size=10))

In [21]:
counts

0    6
1    6
2    4
3    1
4    6
5    1
6    6
7    3
8    5
9    4
dtype: int32

In [22]:
counts.value_counts()

6    4
4    2
1    2
3    1
5    1
Name: count, dtype: int64

### String Methods
`Series` is equipped with a set of string processing methods in the `str` attribute that make it easy to operate on each element of the array. Example:

In [23]:
str_ser = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])

In [24]:
str_ser.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

# Merge
### Concat
` concat()` is used to concatenate pandas objects together.

In [32]:
concat_df = pd.DataFrame(np.random.randn(1000, 5))

In [37]:
# Break the Dataframe into pieces
piece_1 = concat_df[:300]
piece_2 = concat_df[300:700]
piece_3 = concat_df[700:]

In [43]:
# Concatenate the pieces
con_pcs_df = pd.concat([piece_1, piece_2, piece_3])

In [44]:
con_pcs_df

            0         1         2         3         4
0   -1.055095 -0.413235 -2.686937  0.156088  1.212229
1   -2.157084  0.216689 -0.718879 -0.156059  0.336940
2   -2.741728  0.719967 -0.141514  0.100919  1.310500
3    0.285399  0.111322 -0.113450  0.745118 -1.379055
4    0.833337 -0.128423  0.713429  0.046631 -0.103155
..        ...       ...       ...       ...       ...
995 -0.236901  1.601785 -0.815754  0.549965 -0.666139
996 -0.183518 -1.524558  0.507758  0.535277 -0.793815
997 -1.378020 -0.604528 -1.402412 -0.922306 -0.171724
998 -1.225220  0.205442 -1.999872  0.375153 -0.166826
999  1.278273 -0.084401  1.588148  0.690706  0.257646

[1000 rows x 5 columns]

In [45]:
pieces = [concat_df[:300], concat_df[300:700], concat_df[700:]]

In [47]:
pieces

[            0         1         2         3         4
 0   -1.055095 -0.413235 -2.686937  0.156088  1.212229
 1   -2.157084  0.216689 -0.718879 -0.156059  0.336940
 2   -2.741728  0.719967 -0.141514  0.100919  1.310500
 3    0.285399  0.111322 -0.113450  0.745118 -1.379055
 4    0.833337 -0.128423  0.713429  0.046631 -0.103155
 ..        ...       ...       ...       ...       ...
 295  0.270338  1.215428 -0.795508 -0.449773 -0.299899
 296 -0.455113  0.408407 -0.357531  0.548702  1.043466
 297 -0.387139 -0.196392 -1.580742 -2.311404  0.743684
 298 -0.593397  0.239589 -0.433469 -0.602558  0.037688
 299  0.734833 -0.748749  0.047323 -0.069305 -0.326582

 [300 rows x 5 columns],
             0         1         2         3         4
 300 -0.430194  1.666507 -1.285993 -0.724951 -0.317862
 301  0.432308 -1.787039 -0.088335  0.943796 -1.916249
 302 -0.146476 -1.884775 -0.687816  1.515691  0.333634
 303  0.902935  0.109614  1.704535  0.537911  1.054051
 304 -1.036637  0.788221  2.257796 -0.740321  0.354451
 ..        ...       ...       ...       ...       ...
 695  0.316711 -0.715686  0.730059  0.416749  0.425582
 696  0.197836 -1.626816  1.874226 -0.475734 -0.251361
 697  0.049850 -0.109605  0.319468 -0.290792  0.451800
 698  1.106907  0.538904  0.684129  0.032312  1.035837
 699  0.160567 -0.146674 -2.270261  1.043554 -1.182574

 [400 rows x 5 columns],
             0         1         2         3         4
 700 -0.428729 -0.027694  1.738024  1.049361  0.510720
 701 -0.126075 -0.177554  0.300439 -0.732870  0.626085
 702  0.812348 -0.046592 -0.757217 -1.266156 -0.676712
 703  0.192132 -0.007484  1.177205  0.885733  1.791469
 704 -0.498735 -1.378515  0.342046 -2.283584 -0.828630
 ..        ...       ...       ...       ...       ...
 995 -0.236901  1.601785 -0.815754  0.549965 -0.666139
 996 -0.183518 -1.524558  0.507758  0.535277 -0.793815
 997 -1.378020 -0.604528 -1.402412 -0.922306 -0.171724
 998 -1.225220  0.205442 -1.999872  0.375153 -0.166826
 999  1.278273 -0.084401  1.588148  0.690706  0.257646

 [300 rows x 5 columns]]

In [48]:
pd.concat(pieces)

            0         1         2         3         4
0   -1.055095 -0.413235 -2.686937  0.156088  1.212229
1   -2.157084  0.216689 -0.718879 -0.156059  0.336940
2   -2.741728  0.719967 -0.141514  0.100919  1.310500
3    0.285399  0.111322 -0.113450  0.745118 -1.379055
4    0.833337 -0.128423  0.713429  0.046631 -0.103155
..        ...       ...       ...       ...       ...
995 -0.236901  1.601785 -0.815754  0.549965 -0.666139
996 -0.183518 -1.524558  0.507758  0.535277 -0.793815
997 -1.378020 -0.604528 -1.402412 -0.922306 -0.171724
998 -1.225220  0.205442 -1.999872  0.375153 -0.166826
999  1.278273 -0.084401  1.588148  0.690706  0.257646

[1000 rows x 5 columns]

**Note:**

Adding a column to a `DataFrame` is relatively fast. However, adding a row requires a `copy`, and may be expensive. We recommend passing a pre-built list of records to the `DataFrame` constructor rather than building a DataFrame by iteratively appending records.
### Join
`merge()` enables SQL-style join types along specific columns.left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

In [54]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})
right = pd.DataFrame({"key":["foo", "foo"], "rval":[4,5]})

In [55]:
left

   key  lval
0  foo     1
1  foo     2

In [56]:
right

   key  rval
0  foo     4
1  foo     5

In [57]:
# Merging the dataframes

pd.merge(left, right, on='key')

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [58]:
# Merging on unique keys
left = pd.DataFrame({"key": ["foo", "bar"], "lval": [1, 2]})
right = pd.DataFrame({"key":["bar", "foo"], "rval":[4,5]})

In [61]:
left

   key  lval
0  foo     1
1  bar     2

In [62]:
right

   key  rval
0  bar     4
1  foo     5

In [63]:
pd.merge(left, right, on="key")

   key  lval  rval
0  foo     1     5
1  bar     2     4