# Grouping
We use `groupby` to group pandas objects. Grouping refers to one of the following:
1. *Splitting:* Placing data in groups based on a criterion.
2. *Applying:* Apply different functions to each group independently.
3. *Combining:* Combine the result into a data structure.

In [1]:
import numpy as np
import pandas as pd

In [12]:
group_df = pd.DataFrame({
    "A":["foo", "bar", "bar", "foo", "foo", "bar", "bar", "foo"],
    "B":["one", "two", "two", "three", "four", "one", "three", "one"],
    "C": np.random.randn(8),
    "D": np.random.randn(8)
})

In [13]:
group_df

     A      B         C         D
0  foo    one  0.049301  0.235846
1  bar    two  0.290944 -1.049515
2  bar    two  1.373133  0.275281
3  foo  three -0.206334 -1.505266
4  foo   four  1.287007 -2.422463
5  bar    one -0.392782  0.571381
6  bar  three  1.171559 -0.955094
7  foo    one -0.194926  0.437821

Grouping by a column label, selecting column labels, and then applying the `DataFrameGroupBy.sum()` function to the resulting groups:

In [17]:
# Grouping by a single column
group_df.groupby("A")[["C","D",]].sum()

            C         D
A
bar  2.442854 -1.157947
foo  0.935047 -3.254061

In [18]:
# Grouping by multiple columns
group_df.groupby(["A", "B"])[["C", "D"]].sum()

                  C         D
A   B
bar one   -0.392782  0.571381
    three  1.171559 -0.955094
    two    1.664077 -0.774235
foo four   1.287007 -2.422463
    one   -0.145625  0.673668
    three -0.206334 -1.505266