# Reshaping
### Stack
`stack()` method compresses a level in the `DataFrame`'s  columns.

In [3]:
import numpy as np
import pandas as pd

In [4]:
arrays = [
   ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ["one", "two", "one", "two", "one", "two", "one", "two"],
]

In [6]:
index = pd.MultiIndex.from_arrays(arrays, names=['first','second'])
stack_df = pd.DataFrame(np.random.randn(8,2), index=index, columns=["A","B"])

In [7]:
stack_df

                     A         B
first second
bar   one     0.649910  0.776036
      two     1.122857 -3.534360
baz   one    -0.280104 -0.941405
      two    -0.170970  0.092364
foo   one     2.091095 -1.534581
      two    -0.144862 -0.199354
qux   one    -1.944535 -1.382788
      two     1.332570 -0.808902

In [12]:
stack_df_2 = stack_df[:4]

In [13]:
stack_df_2

                     A         B
first second
bar   one     0.649910  0.776036
      two     1.122857 -3.534360
baz   one    -0.280104 -0.941405
      two    -0.170970  0.092364

In [14]:
stacked = stack_df_2.stack()

In [15]:
stacked

first  second
bar    one     A    0.649910
               B    0.776036
       two     A    1.122857
               B   -3.534360
baz    one     A   -0.280104
               B   -0.941405
       two     A   -0.170970
               B    0.092364
dtype: float64

With a “stacked” DataFrame or Series (having a `MultiIndex` as the index), the inverse operation of `stack()` is `unstack()`D, which by default unstacks the last level

In [17]:
stacked.unstack()

                     A         B
first second
bar   one     0.649910  0.776036
      two     1.122857 -3.534360
baz   one    -0.280104 -0.941405
      two    -0.170970  0.092364

In [18]:
stacked.unstack()

                     A         B
first second
bar   one     0.649910  0.776036
      two     1.122857 -3.534360
baz   one    -0.280104 -0.941405
      two    -0.170970  0.092364

### Pivot Tables
`pivot_table()` pivots a `DataFrame` specifying the `values`, `index` and `columns`.

In [19]:
pt_df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "bar", "foo", "bar", "bar", "foo"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),

    }
                    )

In [20]:
pt_df

        A  B    C         D         E
0     one  A  foo -0.277536  1.035641
1     one  B  bar  1.284565  0.297499
2     two  C  foo -1.223894  0.673759
3   three  A  bar -0.691736  0.362114
4     one  B  bar -0.276592  0.013779
5     one  C  foo -1.797330  0.060416
6     two  A  foo  1.669773 -0.001391
7   three  B  bar  0.404656 -1.301156
8     one  C  foo -0.417354 -0.107410
9     one  A  bar -1.748085 -2.949903
10    two  B  bar  1.352372 -0.426871
11  three  C  foo -0.001056 -1.201061

In [21]:
pd.pivot_table(pt_df, values="D", index=["A", "B"], columns=["C"])

C             bar       foo
A     B
one   A -1.748085 -0.277536
      B  0.503987       NaN
      C       NaN -1.107342
three A -0.691736       NaN
      B  0.404656       NaN
      C       NaN -0.001056
two   A       NaN  1.669773
      B  1.352372       NaN
      C       NaN -1.223894